id: IEE6AF4BF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:03:13+00:00'
last_modified: '2022-06-07T13:41:20.983526+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16557
  title: གླུ་འབུམ་པོ་ཏི་དགུ་སྒྲིལ། སྲིད་པའི་གནའ་སྒྲུང་རིང་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C31B:
      image_group_id: I2PD18041
      title: ''
      total_pages: 556
      order: 1
      base_file: C31B.txt
    '5669':
      image_group_id: I2PD18042
      title: ''
      total_pages: 588
      order: 2
      base_file: 5669.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
